[project]
name = "rin-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apscheduler>=3.11.0",
    "openai-agents>=0.0.8",
    "python-dotenv>=1.1.0",
    "uvloop>=0.21.0",
    "vkbottle>=4.4.5",
]
